#!/usr/bin/env bash
set -u

action="${1:-}"
window_id="$(/usr/bin/xdotool getactivewindow 2>/dev/null)"
window_class="$(/usr/bin/xprop -id "$window_id" WM_CLASS 2>/dev/null)"
window_class="${window_class,,}"

if [[ "$window_class" == *terminal* ]]; then
    case "$action" in
        scroll_down|page_down)
            key="shift+Page_Down"
            ;;
        scroll_up|page_up)
            key="shift+Page_Up"
            ;;
        top)
            key="ctrl+shift+Home"
            ;;
        bottom)
            key="ctrl+shift+End"
            ;;
        *)
            /bin/false
            ;;
    esac

    /usr/bin/xdotool windowactivate \
        --sync "$window_id"

    /usr/bin/xdotool key \
        --clearmodifiers "$key"
else
    case "$action" in
        scroll_down)
            /usr/bin/xdotool key \
                --window "$window_id" \
                --clearmodifiers \
                --repeat 4 --delay 50 Down
            ;;
        scroll_up)
            /usr/bin/xdotool key \
                --window "$window_id" \
                --clearmodifiers \
                --repeat 4 --delay 50 Up
            ;;
        page_down)
            /usr/bin/xdotool key \
                --window "$window_id" \
                --clearmodifiers Page_Down
            ;;
        page_up)
            /usr/bin/xdotool key \
                --window "$window_id" \
                --clearmodifiers Page_Up
            ;;
        top)
            /usr/bin/xdotool key \
                --window "$window_id" \
                --clearmodifiers ctrl+Home
            ;;
        bottom)
            /usr/bin/xdotool key \
                --window "$window_id" \
                --clearmodifiers ctrl+End
            ;;
        *)
            /bin/false
            ;;
    esac
fi
